/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AlbumReview model module.
 * @module model/AlbumReview
 * @version 1.0.0
 */
class AlbumReview {
    /**
     * Constructs a new <code>AlbumReview</code>.
     * @alias module:model/AlbumReview
     * @param content {String} 
     * @param rating {Number} 
     * @param album {Number} 
     * @param author {Number} 
     */
    constructor(content, rating, album, author) { 
        
        AlbumReview.initialize(this, content, rating, album, author);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, content, rating, album, author) { 
        obj['content'] = content;
        obj['rating'] = rating;
        obj['album'] = album;
        obj['author'] = author;
    }

    /**
     * Constructs a <code>AlbumReview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AlbumReview} obj Optional instance to populate.
     * @return {module:model/AlbumReview} The populated <code>AlbumReview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AlbumReview();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('content')) {
                obj['content'] = ApiClient.convertToType(data['content'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('album')) {
                obj['album'] = ApiClient.convertToType(data['album'], 'Number');
            }
            if (data.hasOwnProperty('author')) {
                obj['author'] = ApiClient.convertToType(data['author'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
AlbumReview.prototype['id'] = undefined;

/**
 * @member {String} content
 */
AlbumReview.prototype['content'] = undefined;

/**
 * @member {Number} rating
 */
AlbumReview.prototype['rating'] = undefined;

/**
 * @member {Number} album
 */
AlbumReview.prototype['album'] = undefined;

/**
 * @member {Number} author
 */
AlbumReview.prototype['author'] = undefined;






export default AlbumReview;

