/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Album model module.
 * @module model/Album
 * @version 1.0.0
 */
class Album {
    /**
     * Constructs a new <code>Album</code>.
     * @alias module:model/Album
     * @param name {String} 
     * @param reviews {Array.<Number>} 
     */
    constructor(name, reviews) { 
        
        Album.initialize(this, name, reviews);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, reviews) { 
        obj['name'] = name;
        obj['reviews'] = reviews;
    }

    /**
     * Constructs a <code>Album</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Album} obj Optional instance to populate.
     * @return {module:model/Album} The populated <code>Album</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Album();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('release_date')) {
                obj['release_date'] = ApiClient.convertToType(data['release_date'], 'Date');
            }
            if (data.hasOwnProperty('bands')) {
                obj['bands'] = ApiClient.convertToType(data['bands'], ['Number']);
            }
            if (data.hasOwnProperty('artists')) {
                obj['artists'] = ApiClient.convertToType(data['artists'], ['Number']);
            }
            if (data.hasOwnProperty('reviews')) {
                obj['reviews'] = ApiClient.convertToType(data['reviews'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Album.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Album.prototype['name'] = undefined;

/**
 * @member {Date} release_date
 */
Album.prototype['release_date'] = undefined;

/**
 * @member {Array.<Number>} bands
 */
Album.prototype['bands'] = undefined;

/**
 * @member {Array.<Number>} artists
 */
Album.prototype['artists'] = undefined;

/**
 * @member {Array.<Number>} reviews
 */
Album.prototype['reviews'] = undefined;






export default Album;

