/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ArtistBandMembership model module.
 * @module model/ArtistBandMembership
 * @version 1.0.0
 */
class ArtistBandMembership {
    /**
     * Constructs a new <code>ArtistBandMembership</code>.
     * @alias module:model/ArtistBandMembership
     * @param band {Number} 
     * @param artist {Number} 
     * @param startDate {Date} 
     */
    constructor(band, artist, startDate) { 
        
        ArtistBandMembership.initialize(this, band, artist, startDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, band, artist, startDate) { 
        obj['band'] = band;
        obj['artist'] = artist;
        obj['start_date'] = startDate;
    }

    /**
     * Constructs a <code>ArtistBandMembership</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArtistBandMembership} obj Optional instance to populate.
     * @return {module:model/ArtistBandMembership} The populated <code>ArtistBandMembership</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArtistBandMembership();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('band')) {
                obj['band'] = ApiClient.convertToType(data['band'], 'Number');
            }
            if (data.hasOwnProperty('artist')) {
                obj['artist'] = ApiClient.convertToType(data['artist'], 'Number');
            }
            if (data.hasOwnProperty('start_date')) {
                obj['start_date'] = ApiClient.convertToType(data['start_date'], 'Date');
            }
            if (data.hasOwnProperty('end_date')) {
                obj['end_date'] = ApiClient.convertToType(data['end_date'], 'Date');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
ArtistBandMembership.prototype['id'] = undefined;

/**
 * @member {Number} band
 */
ArtistBandMembership.prototype['band'] = undefined;

/**
 * @member {Number} artist
 */
ArtistBandMembership.prototype['artist'] = undefined;

/**
 * @member {Date} start_date
 */
ArtistBandMembership.prototype['start_date'] = undefined;

/**
 * @member {Date} end_date
 */
ArtistBandMembership.prototype['end_date'] = undefined;






export default ArtistBandMembership;

