/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Artist model module.
 * @module model/Artist
 * @version 1.0.0
 */
class Artist {
    /**
     * Constructs a new <code>Artist</code>.
     * @alias module:model/Artist
     * @param name {String} 
     * @param bandMemberships {Array.<Number>} 
     */
    constructor(name, bandMemberships) { 
        
        Artist.initialize(this, name, bandMemberships);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, bandMemberships) { 
        obj['name'] = name;
        obj['band_memberships'] = bandMemberships;
    }

    /**
     * Constructs a <code>Artist</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Artist} obj Optional instance to populate.
     * @return {module:model/Artist} The populated <code>Artist</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Artist();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('band_memberships')) {
                obj['band_memberships'] = ApiClient.convertToType(data['band_memberships'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Artist.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Artist.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} band_memberships
 */
Artist.prototype['band_memberships'] = undefined;






export default Artist;

