/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Band model module.
 * @module model/Band
 * @version 1.0.0
 */
class Band {
    /**
     * Constructs a new <code>Band</code>.
     * @alias module:model/Band
     * @param name {String} 
     * @param artistMemberships {Array.<Number>} 
     */
    constructor(name, artistMemberships) { 
        
        Band.initialize(this, name, artistMemberships);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, artistMemberships) { 
        obj['name'] = name;
        obj['artist_memberships'] = artistMemberships;
    }

    /**
     * Constructs a <code>Band</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Band} obj Optional instance to populate.
     * @return {module:model/Band} The populated <code>Band</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Band();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('artist_memberships')) {
                obj['artist_memberships'] = ApiClient.convertToType(data['artist_memberships'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Number} id
 */
Band.prototype['id'] = undefined;

/**
 * @member {String} name
 */
Band.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} artist_memberships
 */
Band.prototype['artist_memberships'] = undefined;






export default Band;

