/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.OpenapiJsClient);
  }
}(this, function(expect, OpenapiJsClient) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new OpenapiJsClient.Album();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Album', function() {
    it('should create an instance of Album', function() {
      // uncomment below and update the code to test Album
      //var instane = new OpenapiJsClient.Album();
      //expect(instance).to.be.a(OpenapiJsClient.Album);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new OpenapiJsClient.Album();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new OpenapiJsClient.Album();
      //expect(instance).to.be();
    });

    it('should have the property releaseDate (base name: "release_date")', function() {
      // uncomment below and update the code to test the property releaseDate
      //var instance = new OpenapiJsClient.Album();
      //expect(instance).to.be();
    });

    it('should have the property bands (base name: "bands")', function() {
      // uncomment below and update the code to test the property bands
      //var instance = new OpenapiJsClient.Album();
      //expect(instance).to.be();
    });

    it('should have the property artists (base name: "artists")', function() {
      // uncomment below and update the code to test the property artists
      //var instance = new OpenapiJsClient.Album();
      //expect(instance).to.be();
    });

    it('should have the property reviews (base name: "reviews")', function() {
      // uncomment below and update the code to test the property reviews
      //var instance = new OpenapiJsClient.Album();
      //expect(instance).to.be();
    });

  });

}));
